### ISSUE TITLE
Changing mapping FIELD_TYPE breaks drag & drop

### ISSUE THREAD

**Issue by ghost** [dobtco/formbuilder#46] opened 2014-01-17 21:47 UTC
after playing around with the library i decided to customize the mappings to match my schema (and for better naming), but i dicovered that after i change `FIELD_TYPE: 'field_type'` to anything else breaks functionality. More specifically when i drag & drop element it display just the button i dragged in the console there is an error 

```
cannot call method view of undefined
```

on this line

```
((__t = ( Formbuilder.fields[rf.get(Formbuilder.options.mappings.FIELD_TYPE)].view({rf: rf}) )) == null ? '' : __t) +
```

and i don't get why would it break when it evaluates back to a string :(

**Comment by JSlote** [comment] 2014-01-18 21:32
The issue is that the mappings are hard-coded into the templates. The issue is fixed on my fork: github.com/JSlote/formbuilder but I haven’t had time to submit a pull request.

**Closed as completed** 2014-01-19 18:53 UTC

**Comment by ajb** [comment] 2014-01-19 18:55
This is mostly solved, although there's still a hard-coded 'field_options' hash since we're not actually using getters and setters that can handle the dot notation.
